version: '3.8'

services:
  papihairdesign:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./ssl:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro